FROM golang:1.26.5 AS build

WORKDIR /app

COPY go.mod ./
RUN go mod download

COPY cmd ./cmd
COPY pkg ./pkg

RUN CGO_ENABLED=0 go build -ldflags="-w -s" -o /out/daggerlore-api ./cmd

FROM gcr.io/distroless/static-debian12:nonroot

COPY --from=build /out/daggerlore-api /daggerlore-api

ENTRYPOINT ["/daggerlore-api"]
