/**
 * Generates the JSON Schemas for the GM API's `data` payloads from Daggerlore's zod domain schemas, so the
 * contract cannot drift from the schemas the web app validates with. Also parses every hand-written example in
 * docs/api/gm-v1/examples with the zod schema it claims to follow.
 *
 *   npx tsx scripts/gm-api/generate-schemas.ts           # write docs/api/gm-v1/schemas/domain.generated.json
 *   npx tsx scripts/gm-api/generate-schemas.ts --check   # fail when the committed file is stale
 *
 * Refinements (`superRefine`) are not representable in JSON Schema; the OpenAPI document lists them as
 * server-enforced rules (see `x-server-rules` on the affected schemas).
 */
import { readFileSync, readdirSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { z } from 'zod';
import {
	AdversarySchema,
	AncestryCardSchema,
	ArmorSchema,
	BeastformSchema,
	CharacterClassSchema,
	CharacterSheetAddonSchema,
	CommunityCardSchema,
	ConsumableSchema,
	DomainCardSchema,
	DomainSchema,
	EnvironmentSchema,
	LootSchema,
	PrimaryWeaponSchema,
	SecondaryWeaponSchema,
	SubclassSchema,
	TransformationSchema
} from '../../src/lib/domain/schemas/compendium';
import { CountdownSchema, FearSchema } from '../../src/lib/domain/schemas/rules';
import { ConditionSchema } from '../../src/lib/domain/schemas/characters';

const root = join(dirname(fileURLToPath(import.meta.url)), '../../docs/api/gm-v1');

// Keys are the HomebrewTable names from src/lib/domain/permissions.ts.
const homebrew = {
	primary_weapons: PrimaryWeaponSchema,
	secondary_weapons: SecondaryWeaponSchema,
	armor: ArmorSchema,
	loot: LootSchema,
	consumables: ConsumableSchema,
	beastforms: BeastformSchema,
	classes: CharacterClassSchema,
	subclasses: SubclassSchema,
	domains: DomainSchema,
	domain_cards: DomainCardSchema,
	ancestry_cards: AncestryCardSchema,
	community_cards: CommunityCardSchema,
	transformations: TransformationSchema,
	character_sheet_addons: CharacterSheetAddonSchema,
	adversaries: AdversarySchema,
	environments: EnvironmentSchema
} as const;

const shared = {
	countdown: CountdownSchema,
	fear: FearSchema,
	condition: ConditionSchema
} as const;

// The API stores and returns zod's *output* form, which is strict: unknown keys never reach `data` (they live in
// `extensions`). Intersections (`.and`) cannot be strict member by member, so their members are relaxed and the
// composite gets `unevaluatedProperties: false` instead.
function strictenIntersections(node: unknown): void {
	if (Array.isArray(node)) return node.forEach(strictenIntersections);
	if (!node || typeof node !== 'object') return;
	const obj = node as Record<string, unknown>;
	if (Array.isArray(obj.allOf)) {
		for (const member of obj.allOf as Record<string, unknown>[]) {
			if (member && member.additionalProperties === false) delete member.additionalProperties;
		}
		obj.unevaluatedProperties = false;
	}
	Object.values(obj).forEach(strictenIntersections);
}

const toJson = (schema: z.ZodType) => {
	const json = z.toJSONSchema(schema, {
		target: 'draft-2020-12',
		unrepresentable: 'any',
		io: 'output'
	});
	strictenIntersections(json);
	return json;
};

const defs: Record<string, unknown> = {};
for (const [name, schema] of Object.entries({ ...homebrew, ...shared })) {
	const { $schema: _ignored, ...json } = toJson(schema as z.ZodType) as Record<string, unknown>;
	defs[name] = json;
}

const output = {
	$schema: 'https://json-schema.org/draft/2020-12/schema',
	$id: 'https://daggerlore.app/api/gm-v1/schemas/domain.generated.json',
	description:
		'GENERATED by scripts/gm-api/generate-schemas.ts from src/lib/domain/schemas. Do not edit by hand.',
	$defs: defs
};
const text = JSON.stringify(output, null, '\t') + '\n';
const target = join(root, 'schemas/domain.generated.json');

if (process.argv.includes('--check')) {
	let current = '';
	try {
		current = readFileSync(target, 'utf8');
	} catch {
		// treated as stale below
	}
	if (current !== text) {
		console.error('schemas/domain.generated.json is stale; run scripts/gm-api/generate-schemas.ts');
		process.exit(1);
	}
} else {
	writeFileSync(target, text);
}

// Every example must satisfy the zod schema it is filed under.
let failures = 0;
for (const [name, schema] of Object.entries(homebrew)) {
	const file = join(root, 'examples/homebrew', `${name}.json`);
	const parsed = (schema as z.ZodType).safeParse(JSON.parse(readFileSync(file, 'utf8')));
	if (!parsed.success) {
		failures++;
		console.error(`example ${name} is invalid:`, JSON.stringify(parsed.error.issues, null, 2));
	}
}
const unfiled = readdirSync(join(root, 'examples/homebrew')).filter(
	(f) => !(f.replace(/\.json$/, '') in homebrew)
);
if (unfiled.length) {
	failures++;
	console.error('examples without a schema:', unfiled.join(', '));
}
if (failures) process.exit(1);
console.log(
	`ok: ${Object.keys(homebrew).length} homebrew types, ${Object.keys(shared).length} shared`
);
